# Generated by Django 4.0 on 2022-01-06 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_phone_no'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentstripe',
            name='payment_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stripe_payment_from', to='user.user'),
        ),
        migrations.AlterField(
            model_name='paymentstripe',
            name='payment_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stripe_payment_to', to='user.user'),
        ),
    ]
