# Generated by Django 4.0 on 2022-01-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_paymentstripe_payment_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentstripe',
            name='checkout_session_details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='paymentstripe',
            name='checkout_session_id',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='paymentstripe',
            name='payment_details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='paymentstripe',
            name='payment_status',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='paymentstripe',
            name='portal_session_details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
