# Generated by Django 4.0 on 2021-12-22 07:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_name', models.CharField(blank=True, default=None, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_name', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('procedure_price', models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999)])),
                ('hospital_price', models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999)])),
                ('billing_code', models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999)])),
                ('revenue_code', models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999)])),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital', to='hospital.hospital')),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure', to='insurance.insurance')),
            ],
        ),
    ]
