# Generated by Django 4.0 on 2021-12-22 10:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_charge_created_at_charge_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insurance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
