# Generated by Django 4.0 on 2021-12-23 07:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_insurance_created_at_insurance_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge',
            name='hospital_price',
        ),
        migrations.AddField(
            model_name='charge',
            name='maximum_negotiated_price',
            field=models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999)]),
        ),
        migrations.AddField(
            model_name='charge',
            name='minimum_negotiated_price',
            field=models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999)]),
        ),
    ]
