# Generated by Django 4.0 on 2021-12-24 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0006_charge_created_by_insurance_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedure',
            name='insurance',
        ),
        migrations.AddField(
            model_name='charge',
            name='insurance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='insurance.insurance'),
            preserve_default=False,
        ),
    ]
