# Generated by Django 4.0 on 2021-12-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0007_remove_procedure_insurance_charge_insurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='insurance_name',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='procedure_name',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
