# Generated by Django 4.0 on 2021-12-27 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_media'),
        ('insurance', '0008_alter_insurance_insurance_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.CharField(default=None, max_length=250)),
                ('member_id', models.CharField(default=None, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_insurance', to='insurance.insurance')),
            ],
        ),
    ]
