# Generated by Django 3.2.11 on 2022-01-07 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0009_userinsurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='price',
            field=models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999)]),
        ),
    ]
