# Generated by Django 4.0 on 2021-12-28 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0009_userinsurance'),
        ('review', '0002_review_insurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_insurance', to='insurance.insurance'),
        ),
    ]
