# Generated by Django 4.0 on 2022-01-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_review_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='file_field',
            field=models.FileField(blank=True, null=True, upload_to='review_file/'),
        ),
    ]
