# Generated by Django 4.0 on 2021-12-22 07:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('zip_code', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999)])),
            ],
        ),
    ]
