# Generated by Django 4.0 on 2021-12-28 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_hospital_created_by_specialization_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='rating',
            field=models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999)]),
        ),
    ]
