# Generated by Django 4.0 on 2021-12-28 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_hospital_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='rating',
        ),
    ]
