# Generated by Django 4.0 on 2021-12-29 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_hospital_latitude_hospital_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_specialization', to='hospital.specialization'),
        ),
    ]
