# Generated by Django 4.0 on 2022-01-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_hospital_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='hospital_image',
            field=models.FileField(blank=True, null=True, upload_to='hospital_image/'),
        ),
    ]
